from typing import Any
from .awb import Awb, AwbInfo

class AcbWaveformInfo:
    index: int
    name: str
    name_raw: bytes
    filename: str
    size: int

class AcbInfo:
    source_path: str | None
    name: str
    waveform_count: int
    waveforms: list[AcbWaveformInfo]
    embedded_awb: AwbInfo | None

class Acb:
    source_path: str | None
    name: str
    waveform_count: int

    @staticmethod
    def load(source: Any, encoding: str | None = None) -> "Acb": ...
    @staticmethod
    def load_bytes(data: bytes, encoding: str | None = None) -> "Acb": ...
    def info(self, encoding: str | None = None) -> AcbInfo: ...
    def waveform(self, index: int, encoding: str | None = None) -> AcbWaveformInfo: ...
    def waveform_name(self, index: int, encoding: str | None = None) -> str: ...
    def waveform_name_raw(self, index: int) -> bytes: ...
    def waveform_filename(self, index: int, encoding: str | None = None) -> str: ...
    def waveform_bytes(self, index: int) -> bytes: ...
    def extract_waveform_data(self, index: int) -> bytes: ...
    def embedded_awb_bytes(self) -> bytes | None: ...
    def load_awb(self) -> Awb | None: ...
    def extract_file(self, index: int, output_path: Any, encoding: str | None = None) -> None: ...
    def extract(self, output_dir: Any, encoding: str | None = None) -> None: ...

def load(source: Any, *, encoding: str | None = None) -> Acb: ...
def extract(source: Any, output_dir: Any, *, encoding: str | None = None) -> None: ...

__all__: list[str]
