from typing import Any

from .awb import KeyRecoveryResult
from .awb import AacEncryptionState, Awb, AwbInfo

class AcbWaveformInfo:
    index: int
    name: str
    name_raw: bytes
    filename: str

class AcbInfo:
    source_path: str | None
    name: str
    waveform_count: int
    waveforms: list[AcbWaveformInfo]
    table_name: str
    row_count: int
    column_count: int
    has_embedded_awb: bool
    companion_awb_path: str | None
    has_aac_waveforms: bool
    awb_info: AwbInfo | None

class Acb:
    source_path: str | None
    name: str
    waveform_count: int
    has_embedded_awb: bool
    companion_awb_path: str | None
    has_aac_waveforms: bool

    @staticmethod
    def load(source: Any, encoding: str | None = None) -> "Acb": ...
    @staticmethod
    def load_bytes(data: bytes, encoding: str | None = None) -> "Acb": ...
    def info(self) -> AcbInfo: ...
    def waveform(self, index: int) -> AcbWaveformInfo: ...
    def waveform_name(self, index: int) -> str: ...
    def waveform_name_raw(self, index: int) -> bytes: ...
    def waveform_filename(self, index: int, include_index_prefix: bool = True) -> str: ...
    def waveform_bytes(self, index: int, aac_keycode: int = 0) -> bytes: ...
    def extract_waveform_data(self, index: int, aac_keycode: int = 0) -> bytes: ...
    def extract_waveform_stream_data(self, index: int, aac_keycode: int = 0) -> bytes: ...
    def probe_waveform_aac_encryption(self, index: int, keycode: int) -> AacEncryptionState: ...
    def recover_aac_key(self) -> KeyRecoveryResult: ...
    def embedded_awb_bytes(self) -> bytes | None: ...
    def load_awb(self) -> Awb | None: ...
    def extract_file(self, index: int, output_path: Any, aac_keycode: int = 0) -> None: ...
    def extract(self, output_dir: Any, aac_keycode: int = 0) -> None: ...

def load(source: Any, encoding: str | None = None) -> Acb: ...
def extract(source: Any, output_dir: Any, aac_keycode: int = 0, encoding: str | None = None) -> None: ...

__all__: list[str]
