from typing import Any, ClassVar, overload

class AcxEntryType:
    UNKNOWN: ClassVar["AcxEntryType"]
    ADX: ClassVar["AcxEntryType"]
    OGG: ClassVar["AcxEntryType"]

class AcxEntry:
    index: int
    offset: int
    size: int
    type: AcxEntryType
    def suggested_path(self, include_index_prefix: bool = True) -> str: ...

class AcxInfo:
    source_path: str | None
    entry_count: int
    table_size: int
    first_payload_offset: int | None
    payload_end_offset: int | None
    entries: list[AcxEntry]

class AcxBuildEntry:
    source_path: str | None
    data: bytes | None
    def __init__(self, source: Any) -> None: ...

class Acx:
    source_path: str | None
    entry_count: int
    table_size: int
    first_payload_offset: int | None
    payload_end_offset: int | None
    entries: list[AcxEntry]

    @staticmethod
    def load(source: Any) -> "Acx": ...
    @staticmethod
    def load_bytes(data: bytes) -> "Acx": ...
    @staticmethod
    def load_source(source: Any) -> "Acx": ...
    def info(self) -> AcxInfo: ...
    def entry(self, index: int) -> AcxEntry: ...
    def type_count(self, type: AcxEntryType) -> int: ...
    def file_bytes(self, index: int) -> bytes: ...
    def extract_file(self, index: int, output_path: Any) -> None: ...
    def extract(self, output_dir: Any) -> None: ...
    def add_file(self, data: bytes) -> None: ...
    def set_file_data(self, index: int, data: bytes) -> None: ...
    def remove_file(self, index: int) -> None: ...
    def move_file(self, from_index: int, to_index: int) -> None: ...
    def rebuild(self) -> bytes: ...
    @overload
    def save(self) -> bytes: ...
    @overload
    def save(self, output_path: Any) -> None: ...

def load(source: Any) -> Acx: ...
def extract(source: Any, output_dir: Any) -> None: ...
@overload
def build(file_list_path: Any, alignment: int = 4) -> bytes: ...
@overload
def build(file_list_path: Any, output_path: Any, alignment: int = 4) -> None: ...
@overload
def build(entries: list[AcxBuildEntry], alignment: int = 4) -> bytes: ...
@overload
def build(entries: list[AcxBuildEntry], output_path: Any, alignment: int = 4) -> None: ...
def build_to_file(entries: list[AcxBuildEntry], output_path: Any, alignment: int = 4) -> None: ...
def build_from_file_list(file_list_path: Any, alignment: int = 4) -> bytes: ...
def build_file_list_to_file(file_list_path: Any, output_path: Any, alignment: int = 4) -> None: ...

__all__: list[str]
