from typing import Any, ClassVar, overload

class AfsEntryType:
    UNKNOWN: ClassVar["AfsEntryType"]
    ADX: ClassVar["AfsEntryType"]
    HCA: ClassVar["AfsEntryType"]
    OGG: ClassVar["AfsEntryType"]

class AfsHeaderNameMode:
    FILENAME_ONLY: ClassVar["AfsHeaderNameMode"]
    FULL_PATH: ClassVar["AfsHeaderNameMode"]
    CUT_OVERLAPPING_STRING: ClassVar["AfsHeaderNameMode"]

class AfsDirectoryTimestamp:
    year: int
    month: int
    day: int
    hour: int
    minute: int
    second: int
    def __init__(self) -> None: ...
    def empty(self) -> bool: ...

class AfsEntry:
    index: int
    offset: int
    size: int
    type: AfsEntryType
    present: bool
    name: str | None
    header_source_name: str | None
    directory_metadata: bytes
    def is_present(self) -> bool: ...
    def suggested_path(self, include_index_prefix: bool = True) -> str: ...
    def directory_timestamp(self) -> AfsDirectoryTimestamp | None: ...

class AfsInfo:
    source_path: str | None
    entry_count: int
    present_entry_count: int
    alignment: int
    has_directory_table: bool
    is_materialized: bool
    directory_table_offset: int | None
    directory_table_size: int | None
    first_payload_offset: int | None
    entries: list[AfsEntry]

class Afs:
    source_path: str | None
    entry_count: int
    present_entry_count: int
    alignment: int
    has_directory_table: bool
    is_materialized: bool
    directory_table_offset: int | None
    directory_table_size: int | None
    first_payload_offset: int | None
    entries: list[AfsEntry]

    @staticmethod
    def create(alignment: int = ..., include_directory_table: bool = False) -> "Afs": ...
    @staticmethod
    def create_from_als(als_path: Any, alignment: int = ..., include_directory_table: bool = False, source_root: Any | None = None) -> "Afs": ...
    @staticmethod
    def load(source: Any) -> "Afs": ...
    @staticmethod
    def load_bytes(data: bytes) -> "Afs": ...
    @staticmethod
    def load_source(source: Any) -> "Afs": ...
    def info(self) -> AfsInfo: ...
    def entry(self, index: int) -> AfsEntry: ...
    def file_bytes(self, index: int) -> bytes: ...
    def extract_file(self, index: int, output_path: Any) -> None: ...
    def extract(self, output_dir: Any) -> None: ...
    def materialize(self) -> None: ...
    def add_file(self, source_path: Any, name: str | None = None, directory_metadata: bytes = ...) -> None: ...
    def add_file_at_id(self, file_id: int, source_path: Any, name: str | None = None, directory_metadata: bytes = ...) -> None: ...
    def add_bytes(self, data: bytes, name: str | None = None, directory_metadata: bytes = ...) -> None: ...
    def add_bytes_at_id(self, file_id: int, data: bytes, name: str | None = None, directory_metadata: bytes = ...) -> None: ...
    def remove_file(self, index: int) -> None: ...
    def move_file(self, from_index: int, to_index: int) -> None: ...
    def replace_file(self, index: int, source_path: Any) -> None: ...
    def replace_bytes(self, index: int, data: bytes) -> None: ...
    def reserve_file_id(self, file_id: int) -> None: ...
    def set_name(self, index: int, name: str | None) -> None: ...
    def set_header_source_name(self, index: int, source_name: str | None) -> None: ...
    def set_directory_timestamp(self, index: int, timestamp: AfsDirectoryTimestamp | None) -> None: ...
    def set_directory_metadata(self, index: int, directory_metadata: bytes) -> None: ...
    def set_alignment(self, alignment: int) -> None: ...
    def set_directory_table_enabled(self, enabled: bool) -> None: ...
    def set_first_payload_offset(self, offset: int | None = None) -> None: ...
    def build_file_id_header(
        self,
        archive_name: str,
        id_prefix: str = "",
        name_mode: AfsHeaderNameMode = AfsHeaderNameMode.FILENAME_ONLY,
    ) -> str: ...
    @overload
    def save(self) -> bytes: ...
    @overload
    def save(self, output_path: Any) -> None: ...
    def save_bytes(self) -> bytes: ...

def create(alignment: int = ..., include_directory_table: bool = False) -> Afs: ...
def create_from_als(als_path: Any, alignment: int = ..., include_directory_table: bool = False, source_root: Any | None = None) -> Afs: ...
def load(source: Any) -> Afs: ...
def extract(source: Any, output_dir: Any) -> None: ...

__all__: list[str]
