from typing import Any

class AixLayer:
    sample_rate: int
    channel_count: int

class AixLoopInfo:
    start_segment: int
    start_sample: int
    end_segment: int
    end_sample: int

class AixSegment:
    offset: int
    size: int
    sample_count: int
    sample_rate: int

class AixInfo:
    source_path: str | None
    segment_count: int
    layer_count: int
    total_sample_count: int
    inferred_loop: AixLoopInfo | None
    segments: list[AixSegment]
    layers: list[AixLayer]

class AixBuildSegment:
    layer_adx_data: list[bytes]
    def __init__(self, layer_adx_data: Any = ...) -> None: ...

class Aix:
    source_path: str | None
    segments: list[AixSegment]
    layers: list[AixLayer]
    total_sample_count: int
    inferred_loop: AixLoopInfo | None

    @staticmethod
    def load(source: Any) -> "Aix": ...
    @staticmethod
    def load_bytes(data: bytes) -> "Aix": ...
    def info(self) -> AixInfo: ...
    def segment_bytes(self, segment: int, layer: int) -> bytes: ...
    def extract_file(self, segment: int, layer: int, output_path: Any) -> None: ...
    def extract(self, output_dir: Any) -> None: ...
    def save(self) -> bytes: ...
    def save_to_file(self, output_path: Any) -> None: ...
    def add_segment(self, segment: AixBuildSegment) -> None: ...
    def replace_segment(self, index: int, segment: AixBuildSegment) -> None: ...
    def remove_segment(self, index: int) -> None: ...
    def move_segment(self, from_index: int, to_index: int) -> None: ...
    def add_layer(self, segment_adx_data: Any) -> None: ...
    def replace_layer(self, segment_index: int, layer_index: int, data: Any) -> None: ...
    def remove_layer(self, index: int) -> None: ...
    def move_layer(self, from_index: int, to_index: int) -> None: ...

def load(source: Any) -> Aix: ...
def extract(source: Any, output_dir: Any) -> None: ...
def build(segments: Any, output_path: Any | None = None) -> bytes | None: ...
def build_to_file(segments: Any, output_path: Any) -> None: ...

__all__: list[str]
