from typing import Any, ClassVar

class AacEncryptionState:
    INDETERMINATE: ClassVar["AacEncryptionState"]
    CLEAR: ClassVar["AacEncryptionState"]
    ENCRYPTED: ClassVar["AacEncryptionState"]

class AwbEntry:
    offset: int
    size: int
    wave_id: int

class AwbEntryInfo:
    index: int
    wave_id: int
    offset: int
    size: int
    suggested_path: str

class AwbInfo:
    source_path: str | None
    file_count: int
    alignment: int
    version: int
    subkey: int
    id_size: int
    offset_size: int
    entries: list[AwbEntryInfo]

class Awb:
    source_path: str | None
    file_count: int
    alignment: int
    version: int
    subkey: int
    id_size: int
    offset_size: int
    entries: list[AwbEntry]

    @staticmethod
    def create(subkey: int = ...) -> "Awb": ...
    @staticmethod
    def load(source: Any) -> "Awb": ...
    @staticmethod
    def load_bytes(data: bytes) -> "Awb": ...
    def info(self) -> AwbInfo: ...
    def entry_info(self, index: int) -> AwbEntryInfo: ...
    def entry_infos(self) -> list[AwbEntryInfo]: ...
    def file_bytes(self, index: int) -> bytes: ...
    def wave_id(self, index: int) -> int: ...
    def set_wave_id(self, index: int, wave_id: int) -> None: ...
    def add_file(self, source_path: Any, wave_id: int | None = None) -> int: ...
    def add_bytes(self, data: bytes, wave_id: int | None = None) -> int: ...
    def replace_file(self, index: int, source_path: Any) -> None: ...
    def replace_bytes(self, index: int, data: bytes) -> None: ...
    def remove(self, index: int) -> None: ...
    def probe_aac_encryption(self, index: int) -> AacEncryptionState: ...
    def extract_file(self, index: int, output_path: Any) -> None: ...
    def extract(self, output_dir: Any) -> None: ...
    def save(self, output_path: Any | None = None) -> bytes | None: ...
    def save_bytes(self) -> bytes: ...

def create(subkey: int = ...) -> Awb: ...
def load(source: Any) -> Awb: ...
def extract(source: Any, output_dir: Any) -> None: ...

__all__: list[str]
