from typing import Any, ClassVar, Sequence

class AacEncryptionState:
    INDETERMINATE: ClassVar["AacEncryptionState"]
    CLEAR: ClassVar["AacEncryptionState"]
    ENCRYPTED: ClassVar["AacEncryptionState"]

class AwbEntry:
    offset: int
    size: int
    wave_id: int

class KeyCandidate:
    key: int
    score: float
    source_count: int
    validated_sources: int
    candidate_count: int

class KeyRecoveryResult:
    candidates: list[KeyCandidate]
    source_count: int
    evidence_count: int

class AwbInfo:
    source_path: str | None
    file_count: int
    alignment: int
    version: int
    subkey: int
    id_size: int
    offset_size: int
    entries: list[AwbEntry]

class Awb:
    source_path: str | None
    file_count: int
    alignment: int
    version: int
    subkey: int
    id_size: int
    offset_size: int
    entries: list[AwbEntry]
    is_materialized: bool

    @staticmethod
    def create(version: int = ..., alignment: int = ..., subkey: int = ..., id_size: int = ..., offset_size: int = ...) -> "Awb": ...
    @staticmethod
    def load(source: Any) -> "Awb": ...
    @staticmethod
    def load_bytes(data: bytes) -> "Awb": ...
    def info(self) -> AwbInfo: ...
    def entry_info(self, index: int) -> AwbEntry: ...
    def entry_infos(self) -> list[AwbEntry]: ...
    def file_bytes(self, index: int) -> bytes: ...
    def wave_id(self, index: int) -> int: ...
    def set_wave_id(self, index: int, wave_id: int) -> None: ...
    def add_file(self, source_path: Any, wave_id: int | None = None) -> int: ...
    def add_bytes(self, data: bytes, wave_id: int | None = None) -> int: ...
    def replace_file(self, index: int, source_path: Any) -> None: ...
    def replace_bytes(self, index: int, data: bytes) -> None: ...
    def remove(self, index: int) -> None: ...
    def move_file(self, from_index: int, to_index: int) -> None: ...
    def materialize(self) -> None: ...
    def probe_aac_encryption(self, index: int, keycode: int) -> AacEncryptionState: ...
    def recover_aac_key(self) -> KeyRecoveryResult: ...
    def extract_file(self, index: int, output_path: Any) -> None: ...
    def extract(self, output_dir: Any) -> None: ...
    def save(self, output_path: Any | None = None) -> bytes | None: ...
    def save_bytes(self) -> bytes: ...

def create(version: int = ..., alignment: int = ..., subkey: int = ..., id_size: int = ..., offset_size: int = ...) -> Awb: ...
def load(source: Any) -> Awb: ...
def recover_aac_key(source: Any | Sequence[Any], same_base_key: bool = True) -> KeyRecoveryResult: ...
def extract(source: Any, output_dir: Any) -> None: ...

__all__: list[str]
