from typing import Any, ClassVar, overload

class CvmBuildScriptFile:
    index: int
    archive_path: str
    source_path: str

class CvmHeader:
    total_size: int
    chunk_length: int
    sector_table_entry_count: int
    sector_table: list[int]
    iso_start_sector: int
    zone_sector_index: int
    flags: int
    maker_id: str
    filesystem_id: str
    recording_date: str

class CvmZoneLayout:
    sector_length_1: int
    sector_length_2: int
    zone_sector: int
    iso_sector: int
    iso_length: int
    data_sector: int
    data_length: int
    chunk_length: int

class CvmPrimaryVolume:
    system_identifier: str
    volume_identifier: str
    volume_space_size: int
    logical_block_size: int
    volume_set_identifier: str
    publisher_identifier: str
    data_preparer_identifier: str
    application_identifier: str

class CvmEntry:
    index: int
    path: str
    extent_sector: int
    size: int

class CvmDirectoryEntry:
    name: str
    archive_path: str
    size: int
    is_directory: bool

class CvmDirectoryRecord:
    directory_path: str
    extent_sector: int
    byte_size: int
    entries: list[CvmDirectoryEntry]

class CvmRofsFileInfo:
    name: str
    size: int
    is_directory: bool

class CvmRofsVolumeInfo:
    name: str
    source_path: str
    current_directory: str
    is_default: bool
    is_scrambled: bool

class CvmRofsScrambleInfo:
    volume_name: str
    is_scrambled: bool
    initial_sector: int
    current_sector: int
    volume_token: int
    raw_words: tuple[int, ...]

class CvmRofsTransferStatus:
    IDLE: ClassVar["CvmRofsTransferStatus"]
    TRANSFERRING: ClassVar["CvmRofsTransferStatus"]
    COMPLETE: ClassVar["CvmRofsTransferStatus"]
    ERROR: ClassVar["CvmRofsTransferStatus"]

class CvmRofsSeekMode:
    SET: ClassVar["CvmRofsSeekMode"]
    CURRENT: ClassVar["CvmRofsSeekMode"]
    END: ClassVar["CvmRofsSeekMode"]

class CvmRofsRangeHandle:
    volume_name: str
    start_sector: int
    sector_count: int
    byte_size: int
    current_sector: int
    last_transfer_sector_count: int
    last_transfer_status: CvmRofsTransferStatus

class CvmBuildFile:
    archive_path: str
    source_path: str

class CvmBuildInput:
    disc_name: str
    media: str
    system_identifier: str
    volume_identifier: str
    volume_set_identifier: str
    publisher_identifier: str
    data_preparer_identifier: str
    application_identifier: str
    recording_date: str
    files: list[CvmBuildFile]
    from_script: bool
    from_directory: bool

CvmBuildConfig = CvmBuildInput

class CvmInfo:
    source_path: str | None
    entry_count: int
    disc_name: str
    is_scrambled: bool
    has_accessible_contents: bool
    entries: list[CvmEntry]
    header: CvmHeader
    zone: CvmZoneLayout
    primary_volume: CvmPrimaryVolume

class CvmBuildScriptInfo:
    source_path: str | None
    disc_name: str
    media: str
    file_count: int

class CvmBuildScript:
    source_path: str | None
    disc_name: str
    media: str
    system_identifier: str
    volume_identifier: str
    volume_set_identifier: str
    publisher_identifier: str
    data_preparer_identifier: str
    application_identifier: str
    recording_date: str
    files: list[CvmBuildScriptFile]

    @staticmethod
    def load(path: Any) -> "CvmBuildScript": ...
    @staticmethod
    def parse(text: str) -> "CvmBuildScript": ...
    def info(self) -> CvmBuildScriptInfo: ...
    def to_text(self) -> str: ...

class Cvm:
    source_path: str | None
    entry_count: int
    entries: list[CvmEntry]
    header: CvmHeader
    zone: CvmZoneLayout
    primary_volume: CvmPrimaryVolume
    embedded_iso_offset: int
    embedded_iso_size: int
    embedded_iso_sector_count: int
    is_scrambled: bool
    has_accessible_contents: bool
    disc_name: str
    system_identifier: str
    volume_identifier: str
    volume_set_identifier: str
    publisher_identifier: str
    data_preparer_identifier: str
    application_identifier: str
    recording_date: str

    @staticmethod
    def load(source: Any, key: str = "") -> "Cvm": ...
    @staticmethod
    def load_bytes(data: bytes, key: str = "") -> "Cvm": ...
    def info(self) -> CvmInfo: ...
    def entry(self, index: int) -> CvmEntry: ...
    def find_entry(self, path: str) -> CvmEntry | None: ...
    def directory_record(self, path: str = "") -> CvmDirectoryRecord: ...
    def file_bytes(self, index: int) -> bytes: ...
    def file_bytes_at(self, archive_path: str) -> bytes: ...
    def extract_file(self, index: int, output_path: Any) -> None: ...
    def extract(self, output_dir: Any) -> None: ...
    def add_file(self, source_path: Any, archive_path: str) -> int: ...
    def add_bytes(self, data: bytes, archive_path: str) -> int: ...
    def replace_file(self, index: int, source_path: Any) -> None: ...
    def replace_file_at(self, archive_path: str, source_path: Any) -> None: ...
    @overload
    def replace_bytes(self, index: int, data: bytes) -> None: ...
    @overload
    def replace_bytes(self, archive_path: str, data: bytes) -> None: ...
    def replace_bytes_at(self, archive_path: str, data: bytes) -> None: ...
    @overload
    def remove(self, index: int) -> None: ...
    @overload
    def remove(self, archive_path: str) -> None: ...
    def remove_at(self, archive_path: str) -> None: ...
    def move_file(self, from_index: int, to_index: int) -> None: ...
    def rename(self, index: int, archive_path: str) -> None: ...
    def rename_at(self, existing_archive_path: str, archive_path: str) -> None: ...
    @overload
    def save(self, key: str = "") -> bytes: ...
    @overload
    def save(self, output_path: Any, key: str = "") -> None: ...
    def save_bytes(self, key: str = "") -> bytes: ...
    def script_text(self) -> str: ...
    def export_script(self, output_path: Any) -> None: ...

class CvmVolumeSet:
    volume_count: int
    default_volume_name: str | None
    current_directory: str
    status: CvmRofsTransferStatus

    def mount(self, volume_name: str, source: Any) -> None: ...
    def mount_path(self, volume_name: str, path: Any) -> None: ...
    def mount_bytes(self, volume_name: str, data: bytes) -> None: ...
    def unmount(self, volume_name: str) -> None: ...
    def set_default_volume(self, volume_name: str) -> None: ...
    def default_volume(self) -> str | None: ...
    def volume_info(self, volume_name: str) -> CvmRofsVolumeInfo: ...
    def default_volume_info(self) -> CvmRofsVolumeInfo | None: ...
    def switch_image_path(self, volume_name: str, path: Any) -> None: ...
    def switch_image_bytes(self, volume_name: str, data: bytes) -> None: ...
    def find_entry(self, path: str) -> CvmEntry | None: ...
    def directory_record(self, path: str = "") -> CvmDirectoryRecord: ...
    def directory_record_for_volume(self, volume_name: str, path: str = "") -> CvmDirectoryRecord: ...
    def file_exists(self, path: str) -> bool: ...
    def file_exists_relative(self, path: str) -> bool: ...
    def file_size(self, path: str) -> int: ...
    def file_size64(self, path: str) -> int: ...
    def file_size_relative(self, path: str) -> int: ...
    def file_size64_relative(self, path: str) -> int: ...
    def file_bytes(self, path: str) -> bytes: ...
    def file_bytes_relative(self, path: str) -> bytes: ...
    def open_file(self, path: str) -> CvmRofsRangeHandle: ...
    def open_file_relative(self, path: str) -> CvmRofsRangeHandle: ...
    def open_range(self, start_sector: int, sector_count: int, volume_name: str | None = None) -> CvmRofsRangeHandle: ...
    def read_sectors(self, handle: CvmRofsRangeHandle, sector_count: int) -> bytes: ...
    def seek(self, handle: CvmRofsRangeHandle, offset: int, mode: CvmRofsSeekMode = CvmRofsSeekMode.SET) -> int: ...
    def tell(self, handle: CvmRofsRangeHandle) -> int: ...
    def close(self, handle: CvmRofsRangeHandle) -> None: ...
    def stop_transfer(self) -> None: ...
    def transferred_bytes(self) -> int: ...
    def transferred_bytes64(self) -> int: ...
    def change_directory(self, path: str) -> None: ...
    def set_current_directory(self, source: Any) -> None: ...
    def set_current_directory_path(self, path: str) -> None: ...
    def set_current_directory_record(self, record: bytes) -> None: ...
    def set_current_directory_iso(self, sector: int) -> None: ...
    def set_current_directory_iso_count(self, sector: int, count: int) -> None: ...
    def set_current_directory_iso_scramble(self, sector: int, key: str) -> None: ...
    def set_current_directory_iso_count_scramble(self, sector: int, count: int, key: str) -> None: ...
    def load_iso_directory_record(self, sector: int) -> bytes: ...
    def load_rofs_directory_record(self, path: str = "") -> bytes: ...
    def rofs_sector_length(self) -> int: ...
    def rofs_num_files(self) -> int: ...
    def rofs_num_files_for_volume(self, volume_name: str) -> int: ...
    def rofs_num_files_record(self, record: bytes) -> int: ...
    def rofs_num_files_from_record(self, record: bytes) -> int: ...
    def rofs_directory_info(self) -> CvmDirectoryRecord: ...
    def rofs_directory_info_for_volume(self, volume_name: str) -> CvmDirectoryRecord: ...
    def rofs_directory_info_record(self, record: bytes) -> CvmDirectoryRecord: ...
    def rofs_directory_info_from_record(self, record: bytes) -> CvmDirectoryRecord: ...
    def scramble_info(self, volume_name: str | None = None) -> CvmRofsScrambleInfo: ...
    def advance_scramble_info(self, sector_count: int, volume_name: str | None = None) -> CvmRofsScrambleInfo: ...
    def descramble(self, data: bytes, volume_name: str | None = None) -> bytes: ...

def load_script(path: Any) -> CvmBuildScript: ...
def parse_script(text: str) -> CvmBuildScript: ...
def load(source: Any, *, key: str = "") -> Cvm: ...
def extract(source: Any, output_dir: Any, *, key: str = "") -> None: ...
def build(config: CvmBuildInput | CvmBuildScript | Any, output_path: Any | None = None, *, key: str = "") -> bytes | None: ...
def build_from_input(config: CvmBuildInput, *, key: str = "") -> bytes: ...
def build_from_script(config: CvmBuildScript, *, key: str = "") -> bytes: ...
def build_to_file_from_input(output_path: Any, config: CvmBuildInput, *, key: str = "") -> None: ...
def build_to_file_from_script(output_path: Any, config: CvmBuildScript, *, key: str = "") -> None: ...
def export_script(config: CvmBuildInput | CvmBuildScript | Any, output_path: Any | None = None) -> str | None: ...

__all__: list[str]
